config/routes.rb
Rails.application.routes.draw do
  get 'top/about'
  root to: "homes#top"
  devise_for :users
  get 'home/about' => 'homes#about', as: 'about'
  resources :books, only: [:new, :index, :show, :create, :edit, :update,:destroy]
  resources :users, only: [:show, :edit, :update, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :profile_image

         has_many :books, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :book_comments, dependent: :destroy
  
         has_one_attached :profile_image
         validates :name, uniqueness: true
         validates :name, length: { minimum: 2 }
         validates :name, length: { maximum: 20 }
         validates :introduction, length: { maximum: 50 }
  
      def get_profile_image
        if profile_image.attached?
           profile_image.variant(resize_to_limit: [100, 100]).processed
        else
          'default-image.jpg'
      end
   end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @book = Book.new
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="Your request is successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end


  
  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_users.html.erb
<h2>User info</h2>

<table class='table'>
  <tr>
    <%= image_tag user.get_profile_image %>  <!-- 固定値になっているので変数を使いましょう -->
  </tr>
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th>
    <% if user.introduction.present? %>
    <%= user.introduction %>
  <% else %>
    <%= 'none' %>
  <% end %></th>  
  </th>
  </tr>
</table>　

<div class='row'>
   <%= link_to edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block' do %>
  <i class="fa-solid fa-user-gear"></i>
<% end %>
   
</div>



<h2 class="mt-3">New book</h2>




  <%= form_with model: book, url: '/books', method: :post do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title, class: "form-control" %>

    <h4>Body</h4>
    <%= f.text_area :body, class: "form-control" %>

    <%= f.submit 'Create Book', class: "btn btn-success" %>
  <% end %>
</div> 

app/views/users/edit.html.erb
<%= flash[:notice] %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <% if @user.errors.any? %>
        <%= @user.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @user do |f| %>
        <label for="inputName">Name</label>
        </br><%= f.text_field :name, autofocus: true, id:"inputName"%>
        </br><label for="inputImage">Image</label>
        </br><%= f.file_field :profile_image, accept: "image/*" %>  
        </br><label for="inputIntroduction">Introduction</label>
        </br><%= f.text_area :introduction, id: "inputIntroduction"%>
        </br><%= f.submit "Update User", class: "btn btn-secondary" %>
      <% end %>
    </div>  
  </div>  
</div>  
  

app/views/users/index.html.erb
<%= flash[:notice] %>

<div class="container">
  <div class="row">
    <div class="col-md-3">
      
    <%= render 'users', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">  
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= image_tag user.get_profile_image %> 
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "Show", user_path(user) %>
              </td>  
            </tr>  
          <% end %>
        </tbody>  
      </table>  
    </div>      
  </div>  
</div>

app/views/users/show.html.erb
<%= flash[:notice] %>

<div class='container'>
	<div class='row'>
	  <div class='col-md-3'>
      <%= render 'users', book: @book, user: @user %>
		<div>
		
	  <div class='col-md-8 offset-md-1'>
	    <h2>Books</h2>
	    
	    <table class='table table-hover table-inverse'>
	      <thead>
	        <tr>
	          <th></th>
	          <th>Title</th>
	          <th>Opinion</th>
	          <th colspan="3"></th>
	        </tr>
	      </thead>
	      <tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user.id) do %>
								<%= image_tag @user.get_profile_image %>
							<% end %>
						</td>
						<td> 
							<%= link_to book_path(book.id) do %>
								<%= book.title %>
							<% end %> 
						</td>
						<td>   
							<%= book.body %>
						</td>
					</tr>   
				<% end %>
				</tbody>
	    </table>
	  </div>
	</div>
</div>