config/routes.rb
Rails.application.routes.draw do
  get 'top/about'
  root to: "homes#top"
  devise_for :users
  get 'home/about' => 'homes#about', as: 'about'
  resources :books, only: [:new, :index, :show, :create, :edit, :update,:destroy]
  resources :users, only: [:show, :edit, :update, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
    belongs_to :user

    validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
      @book_new = Book.new
      @books = Book.all
      @book = Book.new
      @user = current_user
  end 
  
  def create
      @book_new = Book.new
      @book = Book.new(book_params)
      @book.user_id = current_user.id
      if @book.save
        flash[:notice]="Your request is successfully."
        redirect_to book_path(@book)
      else
        @books =Book.all
        @user = current_user  
        render :index
      end   
  end   

  def show
      @book_new = Book.new
      @book = Book.find(params[:id])
      @user = @book.user
  end   

  def edit
      @book = Book.find(params[:id])
      flash[:notice]="Your request is successfully."
  end   

  def update
      @book = Book.find(params[:id])
      @book.user_id = current_user.id
      if @book.update(book_params)
          flash[:notice]="Your request is successfully."
          redirect_to book_path(@book.id)
      else
          render :edit
      end  
  end   

  def destroy
      book = Book.find(params[:id])
      book.destroy
      flash[:notice]="Your request is successfully."
      redirect_to books_path
  end  

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
      book = Book.find(params[:id])
      unless book.user.id == current_user.id
        redirect_to books_path
      end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>

      <% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

      <%= form_with model: @book do |f| %>
          <label for="inputTitle">Title</label>
          </br><%= f.text_field :title, autofocus: true, id:"inpuTtitle"%> 
          </br><label for="inputBody">Opinion</label>
          </br><%= f.text_area :body, id: "inputBody"%>  
          </br><%= f.submit "Update Book", class: "btn btn-sm btn-success" %>
          </br><%= link_to "Show", book_path(@book.id) %>
          <%= link_to "Back", books_path %>
      <% end %> 
    </div>
  </div>
</div>    

app/views/books/index.html.erb
<%= flash[:notice] %>

<% if @book.errors.any? %>
        <%= @book.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
    <%= render 'users/users', book: @book_new, user: @user %>
    

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3" ></th>
          </tr>
        </thead>
        <tbody>  
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= image_tag book.user.get_profile_image %>
                <% end %> 
              </td>     
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %> 
              </td>   
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>  
      </table>  
    </div>  
  </div>  
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>

<div class='container px-5 px-sm-0'>
	<div class='row'>
	  <div class='col-md-3'>
	    <%= render 'users/users', book: @book_new, user: @user %>
				


	    <div class='col-md-8 offset-md-1'>
	    <h2>Book detail</h2>
	    <table class='table table-hover table-inverse'>
	      <tbody>
					<tr>
						<td>
							<%= image_tag @user.get_profile_image %>
							<br><%= link_to @user.name, user_path(@user) %></br>
						</td>
						<td><%= link_to @book.title, book_path(@book) %></td>
						<td><%= @book.body %></td>
							<% if @book.user == current_user %>
								<td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-success" %></td>
								<td><%= link_to 'Destroy', book_path(@book), method: :delete,class: "btn btn-danger","data-confirm" => "Are you sure?" %></td>
							<% end %>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>