config/routes.rb
Rails.application.routes.draw do
  get 'top/about'
  root to: "homes#top"
  devise_for :users
  get 'home/about' => 'homes#about', as: 'about'
  resources :books, only: [:new, :index, :show, :create, :edit, :update,:destroy]
  resources :users, only: [:show, :edit, :update, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <div class="container">
       <a class="navbar-brand" href="/"><span>Bookers</span></a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
               <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
              <i class="fa-solid fa-house"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-users"></i> Users
              <% end %>
            </li>
            <li>
              <%= link_to "/books", class: 'nav-link text-light' do %>
              <i class="fa-solid fa-book-open"></i> Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fa-solid fa-right-from-bracket"></i> Log out
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to root_path, class:"nav-link text-light" do%>
               <i class="fa-solid fa-house"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to about_path, class:"nav-link text-light" do %>
               <i class="fa-solid fa-link"></i> About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
               <i class="fa-solid fa-user-plus"></i>
               Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class:"nav-link text-light" do %>
               <i class="fa-solid fa-right-to-bracket"></i>
               Log in
              <% end %>
            </li>
          <% end %>
        </ul>
       </div>
      </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/960965aa67.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>